# This file was generated by gen_devices_and_channels.py
# Initialize each device and its channels.

# Device SIS3302
SISInitDevice("SIS3302","0x20000000","125","1","$(READ_THREAD_PRIO)","$(READ_THREAD_STACK)","$(AD_MAX_BUFS)","$(AD_MAX_MEM)")

NDStdArraysConfigure("SIS3302_0",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",0,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_1",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",1,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_2",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",2,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_3",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",3,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_4",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",4,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_5",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",5,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_6",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",6,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
NDStdArraysConfigure("SIS3302_7",$(STDAR_QU_SZ),$(STDAR_BL_CB),"SIS3302_channels",7,$(STDAR_MAX_MEM),$(STDARR_PRI),$(STDAR_ST_SZ))
